<?php
if (empty($this->params)) {
    $this->params = array();
}

if ($this->pageCount): ?>
<ul class="paginationControl">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
    <li>
        <a href="<?php echo $this->url($this->route, array_merge(array('page' => $this->previous), $this->params)); ?>" rel="prev">
            < Previous
        </a> |
    </li>
    <?php else: ?>
    <li>
        <span class="disabled">< Previous</span> |
    </li>
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <li>
            <a href="<?php echo $this->url($this->route,  array_merge(array('page' => $page), $this->params)); ?>">
                <?php echo $page; ?>
            </a> |
        </li>
        <?php else: ?>
        <li>
            <?php echo $page; ?> |
        </li>
        <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
    <li>
        <a href="<?php echo $this->url($this->route,  array_merge(array('page' => $this->next), $this->params)); ?>" rel="next">
            Next >
        </a>
    </li>
    <?php else: ?>
    <li>
        <span class="disabled">Next ></span>
    </li>
    <?php endif; ?>
</ul>
<?php endif; ?>
